export { College } from './College.js';
export { User, Student, Faculty } from './User.js';
export { Department } from './Department.js';
export { Course } from './Course.js';
export { RefreshToken } from './RefreshToken.js';
export { ClassSession } from './ClassSession.js';
export { Attendance } from './Attendance.js';
export { SecurityLog } from './SecurityLog.js';
export { Notification } from './Notification.js';
export { Assignment } from './Assignment.js';
export { Lesson } from './Lesson.js';
export { Exam } from './Exam.js';
export { FeeItem, Transaction } from './Fee.js';
export { AdmissionApplication } from './Admission.js';

export type { ICollege } from './College.js';
export type { IUser, IStudent, IFaculty } from './User.js';
export type { IDepartment } from './Department.js';
export type { ICourse } from './Course.js';
export type { IRefreshToken } from './RefreshToken.js';
export type { IClassSession } from './ClassSession.js';
export type { IAttendance } from './Attendance.js';
export type { ISecurityLog } from './SecurityLog.js';
export type { INotification } from './Notification.js';
export type { IAssignment } from './Assignment.js';
export type { ILesson } from './Lesson.js';
export type { IExam } from './Exam.js';
export type { IFeeItem, ITransaction } from './Fee.js';
export type { IAdmissionApplication } from './Admission.js';
